package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company extends ModelBase implements java.io.Serializable {

	private static final long serialVersionUID = -7321622117023213044L;
	private Long companyId;
	private String companyName;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Company() {
	}

	public Company(String companyName, Set<Contact> contacts) {
		this.companyName = companyName;
		this.contacts = contacts;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@Override
	public String toString() {
		return "Company [companyId=" + companyId + ", companyName="
				+ companyName + "]";
	}
}
