package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * ContactAudit generated by hbm2java
 */
public class ContactAudit implements java.io.Serializable {

	private ContactAuditId id;

	public ContactAudit() {
	}

	public ContactAudit(ContactAuditId id) {
		this.id = id;
	}

	public ContactAuditId getId() {
		return this.id;
	}

	public void setId(ContactAuditId id) {
		this.id = id;
	}

}
