package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * ContactGroupMappingId generated by hbm2java
 */
public class ContactGroupMappingId implements java.io.Serializable {

	private Long contactId;
	private Long groupId;

	public ContactGroupMappingId() {
	}

	public ContactGroupMappingId(Long contactId, Long groupId) {
		this.contactId = contactId;
		this.groupId = groupId;
	}

	public Long getContactId() {
		return this.contactId;
	}

	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactGroupMappingId))
			return false;
		ContactGroupMappingId castOther = (ContactGroupMappingId) other;

		return ((this.getContactId() == castOther.getContactId()) || (this
				.getContactId() != null && castOther.getContactId() != null && this
				.getContactId().equals(castOther.getContactId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this
						.getGroupId() != null && castOther.getGroupId() != null && this
						.getGroupId().equals(castOther.getGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getContactId() == null ? 0 : this.getContactId().hashCode());
		result = 37 * result
				+ (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		return result;
	}

}
