package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * ContactGroupMapping generated by hbm2java
 */
public class ContactGroupMapping implements java.io.Serializable {

	private ContactGroupMappingId id;
	private Groups groups;
	private Contact contact;

	public ContactGroupMapping() {
	}

	public ContactGroupMapping(ContactGroupMappingId id) {
		this.id = id;
	}

	public ContactGroupMapping(ContactGroupMappingId id, Groups groups,
			Contact contact) {
		this.id = id;
		this.groups = groups;
		this.contact = contact;
	}

	public ContactGroupMappingId getId() {
		return this.id;
	}

	public void setId(ContactGroupMappingId id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

}
