package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Department generated by hbm2java
 */
public class Department extends ModelBase implements java.io.Serializable {

	private Long departmentId;
	private String departmentName;
	@JsonIgnore
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Department() {
	}

	public Department(String departmentName, Set<Contact> contacts) {
		this.departmentName = departmentName;
		this.contacts = contacts;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
