package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer id;
	private String address;
	private String area;
	private String company;
	private String department;
	private String designation;
	private String email;
	private int employeeNumber;
	private String firstName;
	private String ipContactNumber;
	private String lastName;
	private String mobileNumber;
	private String priority;
	private String section;

	public Employee() {
	}

	public Employee(String company, String department, String designation,
			int employeeNumber, String firstName, String lastName,
			String mobileNumber, String priority) {
		this.company = company;
		this.department = department;
		this.designation = designation;
		this.employeeNumber = employeeNumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNumber = mobileNumber;
		this.priority = priority;
	}

	public Employee(String address, String area, String company,
			String department, String designation, String email,
			int employeeNumber, String firstName, String ipContactNumber,
			String lastName, String mobileNumber, String priority,
			String section) {
		this.address = address;
		this.area = area;
		this.company = company;
		this.department = department;
		this.designation = designation;
		this.email = email;
		this.employeeNumber = employeeNumber;
		this.firstName = firstName;
		this.ipContactNumber = ipContactNumber;
		this.lastName = lastName;
		this.mobileNumber = mobileNumber;
		this.priority = priority;
		this.section = section;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(int employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getIpContactNumber() {
		return this.ipContactNumber;
	}

	public void setIpContactNumber(String ipContactNumber) {
		this.ipContactNumber = ipContactNumber;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

}
