package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * MessageStatus generated by hbm2java
 */
public class MessageStatus implements java.io.Serializable {

	private MessageStatusId id;
	private Contact contact;
	private MessageLog messageLog;

	public MessageStatus() {
	}

	public MessageStatus(MessageStatusId id) {
		this.id = id;
	}

	public MessageStatus(MessageStatusId id, Contact contact,
			MessageLog messageLog) {
		this.id = id;
		this.contact = contact;
		this.messageLog = messageLog;
	}

	public MessageStatusId getId() {
		return this.id;
	}

	public void setId(MessageStatusId id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public MessageLog getMessageLog() {
		return this.messageLog;
	}

	public void setMessageLog(MessageLog messageLog) {
		this.messageLog = messageLog;
	}

}
