package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MessageLog generated by hbm2java
 */
public class MessageLog implements java.io.Serializable {

	private Long messageLogId;
	private User user;
	private String messageText;
	private String timeoutMilliSec;
	private Date startTime;
	private Date endTime;
	private Set<MessageStatus> messageStatuses = new HashSet<MessageStatus>(0);

	public MessageLog() {
	}

	public MessageLog(Date startTime, Date endTime) {
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public MessageLog(User user, String messageText, String timeoutMilliSec,
			Date startTime, Date endTime, Set<MessageStatus> messageStatuses) {
		this.user = user;
		this.messageText = messageText;
		this.timeoutMilliSec = timeoutMilliSec;
		this.startTime = startTime;
		this.endTime = endTime;
		this.messageStatuses = messageStatuses;
	}

	public Long getMessageLogId() {
		return this.messageLogId;
	}

	public void setMessageLogId(Long messageLogId) {
		this.messageLogId = messageLogId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	public String getTimeoutMilliSec() {
		return this.timeoutMilliSec;
	}

	public void setTimeoutMilliSec(String timeoutMilliSec) {
		this.timeoutMilliSec = timeoutMilliSec;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Set<MessageStatus> getMessageStatuses() {
		return this.messageStatuses;
	}

	public void setMessageStatuses(Set<MessageStatus> messageStatuses) {
		this.messageStatuses = messageStatuses;
	}

}
