package com.sur.balaji.model;

// Generated 7 Oct, 2013 7:45:53 PM by Hibernate Tools 4.0.0

/**
 * MessageTemplate generated by hbm2java
 */
public class MessageTemplate implements java.io.Serializable {

	private Long templateId;
	private String text;

	public MessageTemplate() {
	}

	public MessageTemplate(String text) {
		this.text = text;
	}

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
